/** Mirrors the `profiles.username` check constraint. */
export const USERNAME = /^[a-z0-9_]{3,24}$/;
/** Default handles generated by the sign-up trigger; prompt these users to pick a real one. */
export const DEFAULT_USERNAME = /^birder_[0-9a-f]{6}\d*$/;
